name: portfolio_web_version
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.2.0+1
  flutter_animated_button: ^2.0.3
  google_fonts: ^5.1.0
  url_launcher: ^6.1.12
  web_smooth_scroll: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  fonts:
    - family: madetommy
      fonts:
        - asset: assets/fonts/made_tommy/made_tommy.otf
    - family: madetommybold
      fonts:
        - asset: assets/fonts/made_tommy/made_tommy_bold.otf
    - family: poppinsregular
      fonts:
        - asset: assets/fonts/poppins/poppins_regular.ttf
    - family: poppinsbold
      fonts:
        - asset: assets/fonts/poppins/poppins_bold.ttf
    - family: poppinslight
      fonts:
        - asset: assets/fonts/poppins/poppins_light.ttf
    - family: poppinsthin
      fonts:
        - asset: assets/fonts/poppins/poppins_thin.ttf

  assets:
    - assets/images/
    - assets/images/project/
    - assets/parallax/
    - assets/icons/
    - assets/icons/socialmedia/
    - assets/icons/techstack/
    - assets/icons/techstackcolor/