name: personal_web
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0
configurations:
  [
    {
        name: Flutter Web,
        type: dart,
        request: launch,
        program: lib/main.dart,
        args: [ --web-renderer, html ]
      }
  ]

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  google_fonts: ^5.1.0
  url_launcher: ^6.1.12
  web_smooth_scroll: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: madetommy
      fonts:
        - asset: assets/fonts/made_tommy/made_tommy.otf
    - family: madetommybold
      fonts:
        - asset: assets/fonts/made_tommy/made_tommy_bold.otf
    - family: poppinsregular
      fonts:
        - asset: assets/fonts/poppins/poppins_regular.ttf
    - family: poppinsbold
      fonts:
        - asset: assets/fonts/poppins/poppins_bold.ttf
    - family: poppinslight
      fonts:
        - asset: assets/fonts/poppins/poppins_light.ttf
    - family: poppinsthin
      fonts:
        - asset: assets/fonts/poppins/poppins_thin.ttf

  assets:
    - assets/images/
    - assets/parallax/
    - assets/icons/
    - assets/icons/socialmedia/
    - assets/icons/techstack/
