name: personal_web
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0
configurations:
  [
    {
        name: Flutter Web,
        type: dart,
        request: launch,
        program: lib/main.dart,
        args: [ --web-renderer, html ]
      }
  ]

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: madetommy
      fonts:
        - asset: assets/fonts/made_tommy.otf
    - family: madetommybold
      fonts:
        - asset: assets/fonts/made_tommy_bold.otf

  assets:
    - assets/images/
    - assets/parallax/
