name: portfolio_web_version
description: Manuel Miguez Lauría.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  firebase_storage: ^11.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_animated_button: ^2.0.3
  syncfusion_flutter_pdfviewer: ^23.1.40
  url_launcher: ^6.1.12
  web_smooth_scroll: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/poppins_thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/poppins_light.ttf
          weight: 300
        - asset: assets/fonts/poppins/poppins_regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/poppins_bold.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/images/project/
    - assets/icons/
    - assets/icons/socialmedia/
    - assets/icons/techstack/
    - assets/icons/techstackcolor/
    - assets/gifs/yin-yang-loader.gif
    - assets/pdf/resume.pdf
